package:
  name: py3-click-aliases
  version: 1.0.4
  epoch: 0
  description: enable aliases for click
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-click
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-click
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/click-contrib/click-aliases
      tag: v${{package.version}}
      expected-commit: 6a1922627f09b3de24acd66a81bc7e6fa27fd205

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: click-contrib/click-aliases
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        LIBRARY="click_aliases"
        IMPORT_STATEMENT="Max retries reached."

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
