package:
  name: py3-build
  version: 1.1.1
  epoch: 0
  description: A simple, correct Python build frontend
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-packaging
      - py3-pyproject-hooks
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/build
      tag: ${{package.version}}
      expected-commit: b36126a2b7a387757519029d121da17a38135d67

  - runs: |
      python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 1
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

  - uses: strip

update:
  enabled: true
  github:
    identifier: pypa/build
    use-tag: true
    strip-suffix: .post1

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - uses: python/import
      with:
        import: build
