package:
  name: py3-absl-py
  version: 2.1.0
  epoch: 1
  description: Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
  copyright:
  - license: Apache-2.0
  dependencies:
    runtime:
    - python3
environment:
  contents:
    packages:
    - build-base
    - busybox
    - ca-certificates-bundle
    - py3-setuptools
    - python3
    - wolfi-base
pipeline:
- uses: git-checkout
  with:
    repository: https://github.com/abseil/abseil-py/
    tag: v${{package.version}}
    expected-commit: 8abdd60755e5b6ebfa2b383cf6eaa0d9315335bd
- name: Python Build
  runs: python setup.py build
- name: Python Install
  runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"
- uses: strip
update:
  enabled: true
  github:
    identifier: abseil/abseil-py
    strip-prefix: v
test:
  environment:
    contents:
      packages:
      - busybox
  pipeline:
  - runs: |
      LIBRARY="absl-py"
      python3 -c "import $LIBRARY" 2>/dev/null
      status=$?

      if [ $status -eq 0 ]; then
          echo "Library '$LIBRARY' is installed and can be imported successfully."
          exit 0  # Exit with a status code of 0, indicating success
      else
          echo "Failed to import library '$LIBRARY'. Please check if it is installed."
          exit 1  # Exit with a non-zero status code, indicating failure
      fi
