package:
  name: py3-glpk
  version: 0.4.7
  epoch: 1
  description: PyGLPK, a Python module encapsulating GLPK.
  copyright:
    - license: GPL
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - glpk
      - py3-setuptools
      - py3-setuptools-scm
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: 89a658914b13ae4557b15de945943628c9fc165d46697881027dc39a3dbe9ec3
      uri: https://files.pythonhosted.org/packages/source/g/glpk/glpk-${{package.version}}.tar.gz

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 37380

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        LIBRARY="glpk"
        IMPORT_STATEMENT="import glpk"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
